# LDAP server configuration settings
# Host is a Windows Domain Controller

development:
  host: va.gov
  port: 389
  default_domain: va
  base: va.gov

test:
  host: examplehost
  port: 389
  default_domain: EXAMPLEDOMAIN
  base: examplebase # OU=US-Tampa Bay,OU=North America,OU=Accounts,DC=ourdomain,DC=org

production:
  host: examplehost
  port: 389
  default_domain: EXAMPLEDOMAIN
  base: examplebase # OU=US-Tampa Bay,OU=North America,OU=Accounts,DC=ourdomain,DC=org