module StatesHelper
    def us_states
        [
            ['-Select-', selected: true, disabled: true, class: 'usa-select'],
            ['Alabama', 'AL', class: 'usa-select'],
            ['Alaska', 'AK', class: 'usa-select'],
            ['Arizona', 'AZ', class: 'usa-select'],
            ['Arkansas', 'AR', class: 'usa-select'],
            ['California', 'CA', class: 'usa-select'],
            ['Colorado', 'CO', class: 'usa-select'],
            ['Connecticut', 'CT', class: 'usa-select'],
            ['Delaware', 'DE', class: 'usa-select'],
            ['District of Columbia', 'DC', class: 'usa-select'],
            ['Florida', 'FL', class: 'usa-select'],
            ['Georgia', 'GA', class: 'usa-select'],
            ['Hawaii', 'HI', class: 'usa-select'],
            ['Idaho', 'ID', class: 'usa-select'],
            ['Illinois', 'IL', class: 'usa-select'],
            ['Indiana', 'IN', class: 'usa-select'],
            ['Iowa', 'IA', class: 'usa-select'],
            ['Kansas', 'KS', class: 'usa-select'],
            ['Kentucky', 'KY', class: 'usa-select'],
            ['Louisiana', 'LA', class: 'usa-select'],
            ['Maine', 'ME', class: 'usa-select'],
            ['Maryland', 'MD', class: 'usa-select'],
            ['Massachusetts', 'MA', class: 'usa-select'],
            ['Michigan', 'MI', class: 'usa-select'],
            ['Minnesota', 'MN', class: 'usa-select'],
            ['Mississippi', 'MS', class: 'usa-select'],
            ['Missouri', 'MO', class: 'usa-select'],
            ['Montana', 'MT', class: 'usa-select'],
            ['Nebraska', 'NE', class: 'usa-select'],
            ['Nevada', 'NV', class: 'usa-select'],
            ['New Hampshire', 'NH', class: 'usa-select'],
            ['New Jersey', 'NJ', class: 'usa-select'],
            ['New Mexico', 'NM', class: 'usa-select'],
            ['New York', 'NY', class: 'usa-select'],
            ['North Carolina', 'NC', class: 'usa-select'],
            ['North Dakota', 'ND', class: 'usa-select'],
            ['Ohio', 'OH', class: 'usa-select'],
            ['Oklahoma', 'OK', class: 'usa-select'],
            ['Oregon', 'OR', class: 'usa-select'],
            ['Pennsylvania', 'PA', class: 'usa-select'],
            ['Puerto Rico', 'PR', class: 'usa-select'],
            ['Rhode Island', 'RI', class: 'usa-select'],
            ['South Carolina', 'SC', class: 'usa-select'],
            ['South Dakota', 'SD', class: 'usa-select'],
            ['Tennessee', 'TN', class: 'usa-select'],
            ['Texas', 'TX', class: 'usa-select'],
            ['Utah', 'UT', class: 'usa-select'],
            ['Vermont', 'VT', class: 'usa-select'],
            ['Virginia', 'VA', class: 'usa-select'],
            ['Washington', 'WA', class: 'usa-select'],
            ['West Virginia', 'WV', class: 'usa-select'],
            ['Wisconsin', 'WI', class: 'usa-select'],
            ['Wyoming', 'WY', class: 'usa-select']
        ]
    end
end